on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: blaizek8s.azurecr.io
        username: ${{ secrets.acr_blaizek8s_username }}
        password: ${{ secrets.acr_blaizek8s_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t blaizek8s.azurecr.io/blaizek8s:${{ github.sha }}
        docker push blaizek8s.azurecr.io/blaizek8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_blaizek8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep blaizek8s2559 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace blaizek8s2559`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: blaizek8s2559
        container-registry-url: blaizek8s.azurecr.io
        container-registry-username: ${{ secrets.acr_blaizek8s_username }}
        container-registry-password: ${{ secrets.acr_blaizek8s_password }}
        secret-name: blaizek8sdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: blaizek8s2559
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          blaizek8s.azurecr.io/blaizek8s:${{ github.sha }}
        imagepullsecrets: |
          blaizek8sdockerauth